sudo: required

language: generic
services: docker
env:
  global:
  - TZ='Europe/Oslo'
  - RELEASE_VERSION="$(git fetch --unshallow || true && git rev-list --count $TRAVIS_COMMIT)"
  - DOCKER_IMAGE_FULL_NAME="$TRAVIS_REPO_SLUG:v"
script: docker build -t "$DOCKER_IMAGE_FULL_NAME" .
deploy:
  provider: script
  script: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" && docker push
    "$DOCKER_IMAGE_FULL_NAME"
  on:
    branch: master